--- 
abstract: Configuration File
author: 
  - Matt Luker  C<< <mluker@cpan.org> >>
build_requires: 
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RSH-ConfigFile
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.0
version: 1.0.10
